/** Common countries for investor CRM dropdowns */
export const COUNTRIES = [
  "United Kingdom",
  "United Arab Emirates",
  "Hong Kong",
  "Singapore",
  "United States",
  "India",
  "China",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Germany",
  "France",
  "Switzerland",
  "Ireland",
  "Australia",
  "Canada",
  "South Africa",
  "Nigeria",
  "Pakistan",
  "Malaysia",
  "Other",
] as const;

/** Common nationalities for investor CRM dropdowns */
export const NATIONALITIES = [
  "British",
  "Emirati",
  "Hong Kong",
  "Singaporean",
  "American",
  "Indian",
  "Chinese",
  "Saudi",
  "Qatari",
  "Kuwaiti",
  "Bahraini",
  "German",
  "French",
  "Swiss",
  "Irish",
  "Australian",
  "Canadian",
  "South African",
  "Nigerian",
  "Pakistani",
  "Malaysian",
  "Other",
] as const;
